query Feed {
  posts(take: 10, where: { status: A }, orderBy: { id: desc }) {
    id
    title
    thumbnail
    postedBy {
      id
      name
      avatar
    }
    price
    likeCount
    commentCount
    userLiked
    created
    comments {
      id
      content
      user {
        id
        name
      }
    }
  }
}