query post($id: ID!) {
  post(where: { id: $id}) {
    id
    title
    thumbnail
    postedBy {
      id
      name
      phone
    }
    price
    content
    images
    userLiked
    category {
      title
    }
  }
}