query user($where: UserInput!) {
  user(where: $where, getFollowed: true) {
    id
    name
    followerCount
    followingCount
    address
    posts {
      id
      title
      price
      category {
        title
      }
      regionName
      thumbnail
      userLiked
      created
    }
    isFollowed
  }
}